name: Ethereum Block Fetcher

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]  # Also runs on pushes to main for testing

jobs:
  fetch-blocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install web3
        # Add any other dependencies your script needs
    
    - name: Create data directory
      run: |
        mkdir -p data
    
    - name: Download previous data
      continue-on-error: true
      run: |
        # Try to download the previous data file if it exists
        echo "Attempting to download previous data file..."
        if curl -f -L -o uu_mined_blocks_testnet.json "https://github.com/${{ github.repository }}/releases/latest/download/uu_mined_blocks_testnet.json"; then
          echo "Downloaded previous data file successfully"
          ls -la uu_mined_blocks_testnet.json
        else
          echo "No previous data file found or download failed, starting fresh"
          echo "This is normal for the first run"
        fi
    
    - name: Run Ethereum Block Fetcher
      env:
        RPC_URL: ${{ secrets.RPC_URL }}
      run: |
        # Check if RPC_URL secret is set
        if [ -z "$RPC_URL" ]; then
          echo "Warning: RPC_URL secret not set, using default endpoint"
          echo "Please set RPC_URL secret in repository settings for production use"
        else
          echo "Using RPC_URL from secrets"
        fi
        
        # Run the script
        python ethereum_block_fetcher_github.py
      timeout-minutes: 25  # GitHub Actions has a 6-hour limit, but we want shorter runs
    
    - name: Upload results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mined-blocks-data
        path: |
          uu_mined_blocks_testnet.json
          data/
        retention-days: 30
    
    - name: Create Release with Data
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        tag_name: data-${{ github.run_number }}
        name: "Block Data Update ${{ github.run_number }}"
        files: |
          uu_mined_blocks_testnet.json
        body: |
          Automated block data update
          - Run: ${{ github.run_number }}
          - Timestamp: ${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
